domains                  = "erik.dev.learnf5.cloud"
name                     = "erik"
namespace                = "erik"
origin_pool_service_name = "boutique-frontend.erik"
origin_pool_virtual_site = "erik-vsite"
